//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purchases.Application.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Purchases.Application.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Act as a high-precision optical scanner. Analyze the QR code in this image. Your task is to decode the embedded URL exactly as it is encoded, character by character.
        ///
        ///    First, identify the type of data (e.g., a URL).
        ///    Carefully decode the string.
        ///    Double-check for common URL structures (https, subdomains, parameters).
        ///    Output ONLY the final decoded URL string without any conversational filler..
        /// </summary>
        internal static string ExtractQrCodeBasedOnImage {
            get {
                return ResourceManager.GetString("ExtractQrCodeBasedOnImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role: You are a specialized NFC-e HTML parser. You output only raw valid JSON. No markdown, no backticks, no preamble.
        ///
        ///Input:
        ///
        ///    html_content: The raw HTML of a Brazilian NFC-e receipt.
        ///    source_url: The URL this HTML was saved from.
        ///
        ///Instructions:
        ///
        ///    Extract &amp; Map: Parse the html_content into the schema below. Use null for missing fields.
        ///    Normalization:
        ///        Convert Brazilian numbers (1.234,56) to standard decimals (1234.56).
        ///        Convert dates (03/03/2026 19:00:50) to ISO-8601 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExtractReceiptBasedOnHtmlContent {
            get {
                return ResourceManager.GetString("ExtractReceiptBasedOnHtmlContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brazilian NFC-e Extraction Prompt (Decimal Version)
        ///
        ///You are a specialized Brazilian NFC-e (Nota Fiscal de Consumidor Eletrônica) data extraction engine. Your goal is to convert a receipt image into a high-precision JSON object.
        ///1. Image &amp; OCR Pre-processing
        ///
        ///    The receipt may be rotated or at an angle; mentally deskew before reading.
        ///    Brazilian receipts use a COMMA (,) as a decimal separator. You must convert this to a DOT (.) for the JSON output.
        ///
        ///2. Date &amp; Time Formatting (STRICT - Local Time)
        ///
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExtractReceiptBasedOnImage {
            get {
                return ResourceManager.GetString("ExtractReceiptBasedOnImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are a JSON-only data extraction engine. You never explain, never add markdown, and never add commentary. You only output raw valid JSON.
        ///
        ///Input: A single URL to an NFC-e QR/consultation page: {{URL}}
        ///
        ///Execution Steps:
        ///
        ///    MANDATORY: Use the URL Viewer tool to fetch the content of {{URL}}.
        ///    Once the content is retrieved, extract all available receipt data: merchant, address, NFC-e details, access key, items, totals, payments, and taxes.
        ///    Normalize and output ONLY a single JSON object match [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExtractReceiptBasedOnUrlAndNavigate {
            get {
                return ResourceManager.GetString("ExtractReceiptBasedOnUrlAndNavigate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are an information extraction and classification engine for Brazilian NFC-e (&quot;Documento Auxiliar da Nota Fiscal de Consumidor Eletrônica&quot;) consultation pages.
        ///
        ///Input: a single URL to an NFC-e QR/consultation page, like: {{URL}}
        ///
        ///Task:
        ///
        ///    Open the URL and extract all available receipt data: merchant identification, address, NFC-e number/series, access key, issue datetime, authorization protocol, environment, items (description, product code, quantity, unit, unit price, total price), totals (items [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExtractReceiptBasedOnUrlInfo {
            get {
                return ResourceManager.GetString("ExtractReceiptBasedOnUrlInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do you see in this image?.
        /// </summary>
        internal static string WhatDoYouSee {
            get {
                return ResourceManager.GetString("WhatDoYouSee", resourceCulture);
            }
        }
    }
}
